# Generated by Django 2.1.2 on 2019-05-22 18:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0008_passenger_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='UA', max_length=2),
        ),
    ]
